image: ubuntu:16.04

before_script:
  - apt-get -qq updateq && apt-get -qq install -y lua5.3 make
  - lua5.3 -v

test_diff:
  stage: test
  script:
    - echo -e "\033[36mBuilding initial compiler\033[0m"
    - make
    - echo -e "\033[36mBuilding compiler using new compiler\033[0m"
    - make
    - echo -e "\033[36mComparing output of compiler\033[0m"
    - export TEMP_DIR=$(mktemp -d)
    - make OUT_DIR="$TEMP_DIR"
    - "! (diff -rq \"$TEMP_DIR\" tacky | grep \"$TEMP_DIR\")"

test_run:
  stage: test
  script:
    - echo -e "\033[36mBuilding initial compiler\033[0m"
    - make
    - echo -e "\033[36mRunning tests\033[0m"
    - make test
