image: ubuntu:16.04

before_script:
  - apt-get -qq update && apt-get -qq install -y lua5.3 make
  - lua5.3 -v

test_diff:
  stage: test
  script:
    - echo -e "\033[36mBuilding initial compiler\033[0m"
    - make all
    - echo -e "\033[36mBuilding compiler using new compiler\033[0m"
    - make all
    - echo -e "\033[36mComparing output of compiler\033[0m"
    - export TEMP_DIR=$(mktemp -d)
    - make OUT_DIR="$TEMP_DIR" all
    - "! (diff -rq \"$TEMP_DIR\" tacky | grep \"$TEMP_DIR\")"

test_run:
  stage: test
  script:
    - echo -e "\033[36mBuilding initial compiler\033[0m"
    - make all
    - echo -e "\033[36mRunning tests\033[0m"
    - make test

pages:
  stage: deploy
  before_script:
    - apt-get -qq update && apt-get -qq install -y lua5.3 build-essential ruby-full ruby-dev
    - lua5.3 -v
    - ruby -v
    - gem install jekyll bundler
  script:
    - make docs
    - cd docs
    - bundle
    - bundle exec jekyll build -d ../public
  artifacts:
    paths:
      - public
  only:
    - master
