title: "Urn"
baseurl: /

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "doc"

paginate: 5
paginate_path: "/posts/page-:num/"
